### ISSUE TITLE
Composer Installation Error with Guzzle 6.1

### ISSUE THREAD

**Issue by wutmikee** [mauri870/laravel-linkedin#1]
I'm running Laravel 5.1 and Guzzle 6.1, Laravel latest.

I'm getting this error when i run, `composer require mauri870/laravel-linkedin:dev-master`

```
  Problem 1
    - happyr/linkedin-api-client 0.6.1 requires guzzlehttp/guzzle ~5.0 -> no matching package found.
    - happyr/linkedin-api-client 0.6.0 requires guzzlehttp/guzzle ~5.0 -> no matching package found.
    - mauri870/laravel-linkedin dev-master requires happyr/linkedin-api-client 0.6.* -> satisfiable by happyr/linkedin-api-client[0.6.0, 0.6.1].
    - Installation request for mauri870/laravel-linkedin dev-master -> satisfiable by mauri870/laravel-linkedin[dev-master].
```

**Comment by Nyholm** [comment]
The LinkingIn library depends on Guzzle5 which is incompatible with Guzzle6. There is a PR which makes LinkedIn independent of Guzzle. (https://github.com/Happyr/LinkedIn-API-client/pull/73)
It is going to be merged as soon as [Httplug](http://docs.httplug.io/en/latest/) gets stable. It is currently in alpha.

**Comment by mauri870** [comment]
As soon as Happyr/linkedin-api-client is merged I will cast a new patch for fix this issue with guzzle6, and add a config for choose  what HTTP adapter  to use. For now, use Guzzle5 instead.

**Comment by wutmikee** [comment]
Is there not a branch that you guys could pull in and create a dev version?

**Comment by mauri870** [comment]
The Happyr Linkedin Client is a core of my project, my package is simple a wrapper, an easy usage on laravel framework. All changes in the core must be made in the Happyr package. If modifications are made in my project can break the compatibility with this library. Niholm as already said, as soon as Httplug gets stable he will be merge. The independence of an specific http adapter like Guzzle is the best choice.
